name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install --global web-ext crx3

      - name: Build Firefox XPI (unsigned)
        run: |
          mkdir -p dist/firefox
          rsync -a --exclude 'dist' ./ dist/firefox/
          # Remove background.service_worker (not supported in Firefox)
          jq 'del(.background.service_worker)' dist/firefox/manifest.json > dist/firefox/manifest.tmp.json
          mv dist/firefox/manifest.tmp.json dist/firefox/manifest.json
          web-ext build --source-dir=dist/firefox --overwrite-dest --artifacts-dir=dist/firefox
          for f in dist/firefox/*.zip; do
            mv "$f" "${f%.zip}.xpi"
          done

      - name: Build & Sign Firefox XPI
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        run: |
          mkdir -p dist/firefox-signed
          # Prepare signed source with service_worker removed
          mkdir -p dist/firefox-sign-source
          rsync -a --exclude 'dist' ./ dist/firefox-sign-source/
          jq 'del(.background.service_worker)' dist/firefox-sign-source/manifest.json > dist/firefox-sign-source/manifest.tmp.json
          mv dist/firefox-sign-source/manifest.tmp.json dist/firefox-sign-source/manifest.json

          set +e
          web-ext sign \
            --source-dir=dist/firefox-sign-source \
            --artifacts-dir=dist/firefox-signed \
            --channel=unlisted
          STATUS=$?
          set -e

          if [ $STATUS -ne 0 ]; then
            echo "Signing failed, probably version already exists. Skipping signed XPI."
            rm -f dist/firefox-signed/*.xpi
          else
            # Rename signed XPI to include "-signed"
            for f in dist/firefox-signed/*.xpi; do
              mv "$f" "${f%.xpi}-signed.xpi"
            done
          fi

      - name: Build Chrome CRX and ZIP
        run: |
          mkdir -p dist/chrome
          rsync -a --exclude 'dist' ./ dist/chrome/
          # Remove Firefox-specific fields from manifest
          jq 'del(.background.scripts, .browser_specific_settings)' dist/chrome/manifest.json > dist/chrome/manifest.tmp.json
          mv dist/chrome/manifest.tmp.json dist/chrome/manifest.json
          web-ext build --source-dir=dist/chrome --overwrite-dest --artifacts-dir=dist/chrome
          # Write secret key to file
          echo "${{ secrets.CRX_KEY }}" > dist/chrome/key.pem
          VERSION=$(jq -r '.version' dist/chrome/manifest.json)
          crx3 pack dist/chrome --output dist/chrome/wikitidedebug-$VERSION.crx --key dist/chrome/key.pem
          mv web-extension.crx dist/chrome/wikitidedebug-$VERSION.crx

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          REPO=$(basename $GITHUB_REPOSITORY)
          TAG="v$VERSION"

          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release $TAG already exists, skipping release."
          else
            FILES="dist/firefox/*.xpi"

            # Add signed XPI if it exists
            shopt -s nullglob
            SIGNED=(dist/firefox-signed/*.xpi)
            if [ ${#SIGNED[@]} -ne 0 ]; then
              FILES="$FILES ${SIGNED[@]}"
            fi
            shopt -u nullglob

            FILES="$FILES dist/chrome/*.crx dist/chrome/*.zip"

            gh release create "$TAG" \
              $FILES \
              --title "$REPO $VERSION" \
              --notes "Automated release of $REPO version $VERSION for Firefox (unsigned + signed if available) and Chrome."
          fi
